---
# Source: cachesvc/templates/cnf_tpl_charts_2_3.yaml
#CNF TEMPLATE - NAMESPACE
apiVersion: v1
kind: Namespace
metadata:  
  name: mvnr-ngn-commas
  labels:  
    microSvcName: cachesvc
  annotations:  
    nwFn: commas
    nwFnType: appln
    nwFnPrefix: cache-svc
    svcVersion: v1.0
    overlayha/mode: <coldstandby/hotstandby>
    overlayha/numactive: "<number of active instances>"


# Source: cachesvc/templates/namespace.yaml
apiVersion: v1
kind: Namespace
metadata:
   name: cache-svc
---
# Source: cachesvc/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:  
  name: cachesvc
  namespace: cache-svc
  labels:  
    microSvcName: cachesvc
  annotations:  
    nwFn: commas
    nwFnType: appln
    nwFnPrefix: cache-svc
    svcVersion: v1.0
    overlayha/mode: <coldstandby/hotstandby>
    overlayha/numactive: "<number of active instances>"
spec:
  replicas: 
  selector:
    matchLabels:
      app: cachesvc
  template:
    metadata:  
      name: cachesvc
      namespace: mvnr-ngn-commas
      labels:  
        microSvcName: cachesvc
        app: cachesvc
      annotations:  
        nwFn: commas
        nwFnType: appln
        nwFnPrefix: cache-svc
        svcVersion: v1.0
        overlayha/mode: <coldstandby/hotstandby>
        overlayha/numactive: "<number of active instances>"
    spec:
      initContainers:
      containers:
        -
          imagePullPolicy: Always
          args:
            - -text=commas
          image: xx.xx.xx.xx:yyyy/cachesvc:v0.1
          name: us-cachesvc
          tty: true
          command:
            - /bin/bash
            - -c
            - cachesvc
          env:
            - name: K8S_POD_ID
              valueFrom:
               fieldRef:
                fieldPath: metadata.name
            - name: KAFKA_URL
              value: 0.0.0.0:4222
            - name: KAFKA_TOPIC
              value: AVRO 
          resources:
            limits:
              memory: 200Mi
              cpu: 120m

